### PR TITLE
Add the redirectURL parameter in the signup method

### PR DESCRIPTION
**Pull request by roxanemace**
**Asana ticket**: https://app.asana.com/0/1141396442496489/1199342593301357

### CODE REVIEW

**Comment by rchapel** [comment]
If it's an Url (and from R5 backend implementation it means that it start with `http`), how can I be redirect to my Android application ?

**Comment by roxanemace** [comment]
> If it's an Url (and from R5 backend implementation it means that it start with `http`), how can I be redirect to my Android application ?

It cannot, this link will just allow to overload the "Redirect To" URL set up in the signup template.

**Comment by rchapel** [comment]
> > If it's an Url (and from R5 backend implementation it means that it start with `http`), how can I be redirect to my Android application ?
> 
> It cannot, this link will just allow to overload the "Redirect To" URL set up in the signup template.

It's such a strange user experience, starting in a native App, ending in the browser 🤯 We could allow redirection to a custom-scheme.

**Review by SelimGribaa — APPROVED** [review]

**Comment by roxanemace** [comment]
> > > If it's an Url (and from R5 backend implementation it means that it start with `http`), how can I be redirect to my Android application ?
> > 
> > 
> > It cannot, this link will just allow to overload the "Redirect To" URL set up in the signup template.
> 
> It's such a strange user experience, starting in a native App, ending in the browser 🤯 We could allow redirection to a custom-scheme.

I agree, but redirecting the user to a custom-scheme was not the need specified in the ticket 🤷 It will maybe be done in another ticket.

**Comment by rchapel** [comment]
> > > > If it's an Url (and from R5 backend implementation it means that it start with `http`), how can I be redirect to my Android application ?
> > > 
> > > 
> > > It cannot, this link will just allow to overload the "Redirect To" URL set up in the signup template.
> > 
> > 
> > It's such a strange user experience, starting in a native App, ending in the browser 🤯 We could allow redirection to a custom-scheme.
> 
> I agree, but redirecting the user to a custom-scheme was not the need specified in the ticket 🤷 It will maybe be done in another ticket.

I definitely disagree, If our integrators want to configure this `redirectUrl` in Android it's probably because they want to set a custom-scheme.

**Comment by rchapel** [comment]
Ok actually they can redirect to the browser or to the native app [here](https://developer.android.com/training/app-links)

**Review by FrancoisDevemy5 — APPROVED** [review]

**Pull request merged**
