### PR TITLE
[CA-349] Update du SDK Facebook

### PR DESCRIPTION
**Pull request by nbrr**
[Jira](https://reach5.atlassian.net/browse/CA-349?atlOrigin=eyJpIjoiZTIwOTIxMTk2YzQ2NDNhNWI4OGIxNzQ0YmJiNzllMGQiLCJwIjoiaiJ9)

### CODE REVIEW

**Comment by nbrr** [comment]
On testing @JonathanM90:
- Facebook login with a browser that does not support Custom Pages (e.g. Duckduckgo browser): on the Facebook login page, observe the deprecation warning
- Facebook login with a browser that does support Custom Pages (e.g. Firefox, Chrome): on the Facebook login page, observe that no warning is displayed

**Review by axuan25 — APPROVED** [review]

**Comment by nbrr** [comment]
There are two instances where the facebook login version is defined. One in `app/build.gradle` and one in `sdk-facebook/build.gradle`. I updated both but I noticed that only updating in `sdk-facebook` is enough. I am not sure how versions are resolved. Though commenting the line in `app` prevents form building.

**Comment by nbrr** [comment]
Values in `app/src/main/res/values/settings.xml` seem to be useless. The current values actually are wrong. It seems that having the correct values when configuring the provider in the Reach5 console is what matters.

**Comment by nbrr** [comment]
Note that after the Facebook login, error messages might appear if Webauthn is not enabled or properly configured.

**Review by thomasreach5 — APPROVED** [review]

**Review by roxanemace — APPROVED** [review]

**Pull request merged**
